import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import Header from "./_components/Header";
import Provider from "./Provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <header> */}
            {/* <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn> */}
              {/* <UserButton /> */}
            {/* </SignedIn> */}
            {/* <Header/> */}
          {/* <main>{children}</main> */}

          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
